name: mgcalibrator_env
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.24
  - pandas>=1.5
  - matplotlib>=3.7
  - seaborn>=0.12
  - pysam>=0.20
  - biopython
  - coverm
  - pip
